# Inside application-opensearch.yml
spring:
  ai:
    vectorstore:
      opensearch:
        uris: http://localhost:9200
        
# Custom flags to optimize performance on flat indexes
graphrag:
  pipeline:
    # Options: DEEP (JSON + OCR parser) or LIGHT (Markdown parser)
    strategy: LIGHT
    do-ocr: false
    do-table-structure: false
