include:
  - path: ./temporalio/docker-compose.yml
  - path: ./apache_kafka/docker-compose.yml
  - path: ./docling/docker-compose.yml
  - path: ./neo4j/docker-compose.yml
#  - path: ./opensearch_with_dashboard/docker-compose.yml
#  - path: ./postgres_pgvector
 # - path: ./prometheus_grafana/docker-compose.yml

