services:
  neo4j:
    image: 'neo4j:latest'
    environment:
      - 'NEO4J_AUTH=neo4j/notverysecret'
    ports:
      - '7687'
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  typesense:
    image: 'typesense/typesense:30.1'
    environment:
      - 'TYPESENSE_API_KEY=secret'
      - 'TYPESENSE_DATA_DIR=/tmp'
    ports:
      - '8108'
  weaviate:
    image: 'semitechnologies/weaviate:latest'
    ports:
      - '8080'
