spring:
  application:
    name: vsbus
  kafka:
    bootstrap-servers: localhost:9092
# Serializers required to translate your keys and values to byte arrays
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
