spring:
  application:
    name: woodchuck
  main:
    web-application-type: NONE
    keep-alive: false
  profiles:
    active: dev
  temporal:
    start-workers: true
    workers:
      - task-queue: BioTaskQueue
        capacity:
          max-concurrent-workflow-task-pollers: 6
          max-concurrent-activity-task-pollers: 6
        rate-limits:
          max-worker-activities-per-second: 0
          max-task-queue-activities-per-second: 0
    workflow-cache:
      max-instances: 10
      max-threads: 10
    connection:
      target: localhost:7233
    workers-auto-discovery:
      packages:
        - "org.woodchuck.temporal"


app:
  runner:
    enabled: false
    temporal-citation-enabled: false
    temporal-rcsb-enabled: true
  temporal:
    bio:
      search:
        timeout-seconds: 15
        initial-interval-seconds: 1
        backoff-coefficient: 2.0
        maximum-interval-seconds: 10
        maximum-attempts: 3
      data:
        timeout-seconds: 30
        initial-interval-seconds: 2
        backoff-coefficient: 2.0
        maximum-interval-seconds: 20
        maximum-attempts: 5
