arconia:
  dev:
    services:
      docling:
        enabled: true
        base-url: ghttp://localhost:5001

management:
  endpoint:
    health:
      show-components: always

server:
  port: 8085 # Port for your REST API
spring:
  application:
    name: gaZap-backend
  profiles:
    active: dev
  temporal:
    start-workers: true
    workers:
      - task-queue: BioTaskQueue
        capacity:
          max-concurrent-workflow-task-pollers: 6
          max-concurrent-activity-task-pollers: 6
        rate-limits:
          max-worker-activities-per-second: 0
          max-task-queue-activities-per-second: 0
    workflow-cache:
      max-instances: 10
      max-threads: 10
    connection:
      target: localhost:7233
    workers-auto-discovery:
      packages:
        - "org.woodchuck.temporal"


# app:
#   runner:
#     enabled: false
#     temporal-citation-enabled: false
#     temporal-rcsb-enabled: true
#   temporal:
#     bio:
#       search:
#         timeout-seconds: 15
#         initial-interval-seconds: 1
#         backoff-coefficient: 2.0
#         maximum-interval-seconds: 10
#         maximum-attempts: 3
#       data:
#         timeout-seconds: 30
#         initial-interval-seconds: 2
#         backoff-coefficient: 2.0
#         maximum-interval-seconds: 20
#         maximum-attempts: 5
